# Generated by Django 3.2.9 on 2021-12-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'events', 'verbose_name_plural': 'events'},
        ),
    ]
