# Generated by Django 3.2.9 on 2021-12-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'team'},
        ),
    ]
