# Generated by Django 3.2.9 on 2021-12-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
