# Generated by Django 3.2.9 on 2021-12-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='closing_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='opening_time',
            field=models.IntegerField(null=True),
        ),
    ]
