# Generated by Django 3.2.9 on 2021-12-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20211208_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='opening_time',
        ),
        migrations.AlterField(
            model_name='table',
            name='table_size',
            field=models.CharField(choices=[('two persons', 'TWO PERSONS'), ('four persons', 'FOUR PERSONS'), ('six persons', 'SIX PERSONS'), ('eight persons', 'EIGHT PERSONS')], max_length=15),
        ),
    ]
