# Generated by Django 3.2.9 on 2021-12-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20211209_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='nr_of_people',
        ),
    ]
