# Generated by Django 3.2.9 on 2021-12-09 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_reservation_nr_of_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date_time_end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date_time_start',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.IntegerField(choices=[('17:00 - 18:30', '17:00'), ('19:00 - 20:30', '19:00'), ('21:00 - 22:30', '21:00')], null=True),
        ),
    ]
