# Generated by Django 3.2.9 on 2021-12-09 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20211209_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 15, 2, 27, 399369, tzinfo=utc)),
        ),
    ]
