# Generated by Django 3.2.9 on 2021-12-09 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 15, 27, 6, 58446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.IntegerField(choices=[('17:00 - 18:30', '17:00 - 18:30'), ('19:00 - 20:30', '19:00 - 20:30'), ('21:00 - 22:30', '21:00 - 22:30')], default=2),
            preserve_default=False,
        ),
    ]
