# Generated by Django 3.2.9 on 2021-12-09 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20211209_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_time_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 17, 9, 29, 543403, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 17, 9, 29, 543375, tzinfo=utc)),
        ),
    ]
