# Generated by Django 3.2.9 on 2021-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20211209_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_time_start',
            field=models.DateTimeField(),
        ),
    ]
