# Generated by Django 3.2.9 on 2021-12-10 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_auto_20211209_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_time_end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_time_start',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
