# Generated by Django 3.2.9 on 2021-12-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_detail',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='reservation.customer'),
            preserve_default=False,
        ),
    ]
