# Generated by Django 3.2.9 on 2021-12-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
