# Generated by Django 3.2.9 on 2021-12-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_reservation_customer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.customer', unique=True),
        ),
    ]
