# Generated by Django 3.2.9 on 2021-12-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_alter_reservation_customer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_detail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.customer'),
        ),
    ]
